class CoreApiException(Exception): ...


class DatabaseException(CoreApiException): ...


class DuplicateException(CoreApiException): ...


class NotFoundException(CoreApiException): ...


class LLMException(CoreApiException): ...



class LLMAuthenticationException(LLMException): ...



class LLMQuotaExhaustedException(LLMException): ...



class LLMConnectionException(LLMException): ...