class CoreApiException(Exception): ...


class InvitationNotFound(CoreApiException): ...


class EmailAlreadyUsed(CoreApiException): ...


class IncorrectPassword(CoreApiException): ...


class HashingFailed(CoreApiException): ...


class SendEmailFailed(CoreApiException): ...


class DatabaseException(CoreApiException): ...


class DuplicateException(DatabaseException): ...


class NotFoundException(DatabaseException): ...


class ResourceExpired(CoreApiException): ...


class JWTException(CoreApiException): ...


class InvalidToken(JWTException): ...


class TokenExpired(JWTException, ResourceExpired): ...


class TokenCreationFailed(JWTException): ...


class InviteAlreadySent(CoreApiException): ...


class UnauthorizedAccessException(CoreApiException): ...


class BlobOperationException(CoreApiException): ...


class BlobAlreadyExistsError(BlobOperationException): ...


class BlobNotFoundError(BlobOperationException): ...
